#!/bin/sh
# Regenerate driver/oo_horn_generated.ML from the verified theories.
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
TMP=$(mktemp -d)
isabelle build -d "$HERE" -e OOHorn
isabelle export -d "$HERE" -x "OOHorn.OO_Export:code/oo_horn.ML" -O "$TMP" OOHorn
{ echo "(* GENERATED BY isabelle build -e FROM isabelle/OO_Export.thy -- DO NOT EDIT."
  echo "   Regenerate with isabelle/export.sh.  Isabelle2025-2, session OOHorn. *)"
  cat "$TMP/OOHorn.OO_Export/code/oo_horn.ML"
} > "$HERE/driver/oo_horn_generated.ML"
rm -rf "$TMP"
echo "wrote $HERE/driver/oo_horn_generated.ML"
